# Generated by Django 5.0.3 on 2024-03-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='answers',
            name='date',
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.PositiveSmallIntegerField(choices=[(1, 'aaaa'), (2, 'bbbb'), (3, 'cccc'), (4, 'dddd'), (5, 'eeee'), (6, 'ffff')], verbose_name='Answer'),
        ),
    ]
