# Generated by Django 5.0.3 on 2024-03-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_answers_options_remove_answers_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
    ]
