# Generated by Django 5.0.3 on 2024-03-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_response_correct_answer_question1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='correct_answer_question1',
        ),
        migrations.RemoveField(
            model_name='response',
            name='correct_answer_question2',
        ),
        migrations.AlterField(
            model_name='response',
            name='question1',
            field=models.CharField(choices=[('option1', '«Иван-царевич и Серый волк»'), ('option2', '«Царевна-лягушка»'), ('option3', '«Сказка о царе Салтане»')], max_length=200),
        ),
        migrations.AlterField(
            model_name='response',
            name='question2',
            field=models.CharField(choices=[('option1', '«Судьба человека»'), ('option2', '«Война и мир»'), ('option2', '«Сын полка»')], max_length=200),
        ),
    ]
